# Generated by Django 5.2 on 2025-05-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postings", "0002_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="activity/%Y/%m/%d"
            ),
        ),
    ]
