# Generated by Django 5.2 on 2025-05-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postings", "0003_activity_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="posts/"),
        ),
    ]
