#databases:
#  - name: chebz
#    plan: free
#    databaseName: Chebz
#    user: postgres
#
#services:
#  - type: web
#    plan: free
#    name: Chebz
#    runtime: python
#    buildCommand: './build.sh'
#    startCommand: 'python -m gunicorn Chebz.asgi:application -k uvicorn.workers.UvicornWorker'
#    envVars:
#      - key: DATABASE_URL
#        fromDatabase:
#          name: chebz
#          property: connectionString
#      - key: SECRET_KEY
#        generateValue: true
#      - key: WEB_CONCURRENCY
#        value: 4


databases:
  - name: chebzdb
    plan: free
    databaseName: chebzdb
    user: chebzuser

services:
  - type: web
    name: chebzapp
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: >
      gunicorn Chebz.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chebzdb
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: Chebz.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: 'chebzapp.onrender.com'
      - key: WEB_CONCURRENCY
        value: '4'
